version: '3'

services:
  auth_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - ./.env:/app/.env
